/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file matmul_a16w16_block_mmad_swat.h
 * \brief Block-level A16W16 MMAD pipeline for SWAT non-full-load path.
 */

#pragma once

#include "kernel_utils/common_utils.h"
#include "kernel_utils/layout_utils.h"
#include "kernel_utils/tuple_utils.h"
#include "block_mmad.h"
#include "include/tensor.h"
#include "../policy/dispatch_policy.h"
#include "../utils/matmul_a16w16_constant.h"

namespace Block {
using namespace AscendC;

// Custom mmadTrait internal value type
constexpr AscendC::Te::MmadTrait MMAD_TRAIT{0, false, false, true, AscendC::Te::MmadType::NORMAL}; // disableGemv=true

struct MmadMmTraitConfig { // Custom Trait class
    using TraitType = AscendC::Te::MmadTrait;
    static constexpr const TraitType value = MMAD_TRAIT;
};

template <
    class DispatchPolicy_, class TypeA_, class LayoutA_, class TypeB_, class LayoutB_, class TypeC_, class LayoutC_>
class BlockMmad<
    DispatchPolicy_, TypeA_, LayoutA_, TypeB_, LayoutB_, TypeC_, LayoutC_,
    AscendC::Std::enable_if_t<
        AscendC::Std::is_base_of_v<MatmulA16W16MultiBlockWithSwat<NO_FULL_LOAD_MODE>, DispatchPolicy_>>> {
public:
    using TypeA = TypeA_;
    using TypeB = TypeB_;
    using TypeC = TypeC_;
    using LayoutA = LayoutA_;
    using LayoutB = LayoutB_;
    using DispatchPolicy = DispatchPolicy_;
    using TupleShape = AscendC::Shape<int64_t, int64_t, int64_t>;
    using BlockShape = AscendC::Shape<int64_t, int64_t, int64_t, int64_t>;
    static constexpr bool transA = TagToTrans<LayoutA>::value;
    static constexpr bool transB = TagToTrans<LayoutB>::value;
    using MakeLayoutAL1 =
        AscendC::Std::conditional_t<transA, AscendC::Te::ZnLayoutFormat<TypeA>, AscendC::Te::NzLayoutFormat<TypeA>>;
    using MakeLayoutBL1 =
        AscendC::Std::conditional_t<transB, AscendC::Te::ZnLayoutFormat<TypeB>, AscendC::Te::NzLayoutFormat<TypeB>>;
    uint64_t m_{1};
    uint64_t n_{1};
    uint64_t k_{1};
    uint64_t kAlign_{1};
    uint64_t kL1Iter_{0};
    uint64_t mL1_{1};
    uint64_t nL1_{1};
    uint64_t kL1_{1};
    uint64_t baseM_{16};
    uint64_t baseN_{16};
    uint64_t baseK_{16};
    constexpr static uint64_t L1_BUFFER_NUM = 2;
    constexpr static uint64_t BUFFER_NUM = 2;
    constexpr static uint64_t SPLIT_M_ALIGN = 2;
    constexpr static uint64_t HALF_L0_SIZE = L0A_SIZE / DOUBLE_BUFFER_COUNT / sizeof(TypeA);
    constexpr static uint64_t HALF_L0C_SIZE = L0C_SIZE / DOUBLE_BUFFER_COUNT / sizeof(float);
    // C0_SIZE equals 8 in order to adapt to the fp32 matrix
    constexpr static int32_t C0_SIZE = AscendC::AuxGetC0Size<TypeA>();
    constexpr static uint64_t halfL0Size_ = L0AUF_SIZE / BUFFER_NUM / sizeof(TypeA);
    // Set unitflag state: 3 = final accumulation, 2 = non-final accumulation
    constexpr static uint32_t FINAL_ACCUMULATION = 3;
    constexpr static uint32_t NON_FINAL_ACCUMULATION = 2;
    constexpr static uint64_t BLOCK_BYTE_SIZE = 32;
    uint64_t abL1LoopCnt_{0};
    uint64_t l0PingPong_{0};
    uint64_t l0cPingPong_{0};
    bool enableL0cPingPong_{false};
    bool splitM_{false};
    struct Params {
        GM_ADDR aGmAddr{nullptr};
        GM_ADDR bGmAddr{nullptr};
        GM_ADDR cGmAddr{nullptr};
    };

    __aicore__ inline BlockMmad()
    {
        AscendC::SetFlag<AscendC::HardEvent::MTE1_MTE2>(ZERO_FLAG);
        AscendC::SetFlag<AscendC::HardEvent::MTE1_MTE2>(FIRST_FLAG);
        AscendC::SetFlag<AscendC::HardEvent::FIX_M>(ZERO_FLAG);
        AscendC::SetFlag<AscendC::HardEvent::FIX_M>(FIRST_FLAG);
        // Distinguish flagid of TPIPE generated by automatic fusion
        AscendC::SetFlag<AscendC::HardEvent::M_MTE1>(SIXTH_FLAG);
        AscendC::SetFlag<AscendC::HardEvent::M_MTE1>(SEVENTH_FLAG);
    }

    __aicore__ inline ~BlockMmad()
    {
        AscendC::WaitFlag<AscendC::HardEvent::MTE1_MTE2>(ZERO_FLAG);
        AscendC::WaitFlag<AscendC::HardEvent::MTE1_MTE2>(FIRST_FLAG);
        AscendC::WaitFlag<AscendC::HardEvent::FIX_M>(ZERO_FLAG);
        AscendC::WaitFlag<AscendC::HardEvent::FIX_M>(FIRST_FLAG);
        // Distinguish flagid of TPIPE generated by automatic fusion
        AscendC::WaitFlag<AscendC::HardEvent::M_MTE1>(SIXTH_FLAG);
        AscendC::WaitFlag<AscendC::HardEvent::M_MTE1>(SEVENTH_FLAG);
    }

    __aicore__ inline void Init(
        const TupleShape& problemShape, const TupleShape& tileL1Shape, const TupleShape& tileL0Shape, bool l0cDB)
    {
        m_ = Get<IDX_M_IDX>(problemShape);
        n_ = Get<IDX_N_IDX>(problemShape);
        k_ = Get<IDX_K_IDX>(problemShape);
        mL1_ = Get<IDX_M_IDX>(tileL1Shape);
        nL1_ = Get<IDX_N_IDX>(tileL1Shape);
        kL1_ = Get<IDX_K_IDX>(tileL1Shape);
        baseM_ = Get<IDX_M_IDX>(tileL0Shape);
        baseN_ = Get<IDX_N_IDX>(tileL0Shape);
        baseK_ = Get<IDX_K_IDX>(tileL0Shape);
        kAlign_ = Align(k_, AscendC::BLOCK_CUBE);
        enableL0cPingPong_ = l0cDB;
        // Non-full load
        aL1OneBuffer_ = mL1_ * kL1_;
        bL1Init_ = aL1OneBuffer_ * L1_BUFFER_NUM;
        bL1OneBuffer_ = nL1_ * kL1_;
        kL1Iter_ = CeilDiv(k_, kL1_); // k_ >= kL1_
        l0PingPong_ = 0;
        abL1LoopCnt_ = 0;
        l0cPingPong_ = 0;
    }

    template <typename TensorC, typename TensorA, typename TensorB>
    __aicore__ inline void operator()(TensorC gmC, TensorA gmA, TensorB gmB, const BlockShape& tileShape)
    {
        uint64_t curM = Get<MNK_M>(tileShape);
        uint64_t curN = Get<MNK_N>(tileShape);
        uint64_t ml1Align = Align(curM, AscendC::BLOCK_CUBE);
        uint64_t l0cOffset = (l0cPingPong_ & 0x1) * HALF_L0C_SIZE;
        if (enableL0cPingPong_) {
            AscendC::WaitFlag<AscendC::HardEvent::FIX_M>(l0cPingPong_ & 0x1);
        }
        kL1_ = Min(k_, kL1_);

        // LoC move out
        auto layoutL0C = AscendC::Te::MakeL0CLayout(curM, curN);
        auto tensorL0C =
            AscendC::Te::MakeTensor(AscendC::Te::MakeL0CmemPtr<float>(l0cOffset * sizeof(float)), layoutL0C);

        kL1Iter_ = CeilDiv(k_, kL1_); // k_ >= kL1_
        for (uint64_t iter0 = 0; iter0 < kL1Iter_; ++iter0) {
            auto curKL1 = (iter0 + 1 == kL1Iter_) ? (k_ - iter0 * kL1_) : kL1_;

            uint64_t l1BufId = abL1LoopCnt_ & (L1_BUFFER_NUM - 1);
            uint64_t offsetAl1 = aL1OneBuffer_ * l1BufId;
            AscendC::WaitFlag<AscendC::HardEvent::MTE1_MTE2>(l1BufId);
            uint64_t offsetBl1 = bL1Init_ + bL1OneBuffer_ * l1BufId;

            // A GM->L1
            auto layoutAL1 = MakeLayoutAL1{}(static_cast<int64_t>(curM), static_cast<int64_t>(curKL1));
            auto copyGM2L1 = AscendC::Te::MakeCopy(AscendC::Te::CopyGM2L1{});
            auto tensorAL1 =
                AscendC::Te::MakeTensor(AscendC::Te::MakeL1memPtr<TypeA>(offsetAl1 * sizeof(TypeA)), layoutAL1);
            // Slice first
            auto gmTileA = gmA(AscendC::Te::MakeCoord(0, iter0 * kL1_), AscendC::Te::MakeShape(curM, curKL1));
            // Copy AL1
            AscendC::Te::Copy(copyGM2L1, tensorAL1, gmTileA);

            // B GM->L1
            auto layoutBL1 = MakeLayoutBL1{}(static_cast<int64_t>(curKL1), static_cast<int64_t>(curN));
            auto tensorBL1 =
                AscendC::Te::MakeTensor(AscendC::Te::MakeL1memPtr<TypeB>(offsetBl1 * sizeof(TypeB)), layoutBL1);
            // Slice first
            auto gmTileB = gmB(AscendC::Te::MakeCoord(iter0 * kL1_, 0), AscendC::Te::MakeShape(curKL1, curN));
            // Copy BL1
            AscendC::Te::Copy(copyGM2L1, tensorBL1, gmTileB);

            AscendC::SetFlag<AscendC::HardEvent::MTE2_MTE1>(l1BufId);
            AscendC::WaitFlag<AscendC::HardEvent::MTE2_MTE1>(l1BufId);

            uint64_t kL0Iter = (curKL1 + baseK_ - 1) / baseK_;
            for (uint64_t iter1 = 0; iter1 < kL0Iter; ++iter1) {
                uint64_t curK0 = (iter1 + 1 == kL0Iter) ? (curKL1 - iter1 * baseK_) : baseK_;
                uint64_t l0Offset = HALF_L0_SIZE * (l0PingPong_ & 0x1);
                uint64_t mte1Flag = ((l0PingPong_ & 0x1) + SIXTH_FLAG);
                AscendC::WaitFlag<AscendC::HardEvent::M_MTE1>(static_cast<uint16_t>(mte1Flag));

                // A L1->L0
                auto copyL12L0 = AscendC::Te::MakeCopy(AscendC::Te::CopyL12L0{});
                auto layoutAL0 = AscendC::Te::MakeNzLayout<TypeA>(curM, curK0);
                auto tensorAL0 =
                    AscendC::Te::MakeTensor(AscendC::Te::MakeL0AmemPtr<TypeA>(l0Offset * sizeof(TypeA)), layoutAL0);
                auto tensorBlockAL1 =
                    tensorAL1(AscendC::Te::MakeCoord(0, iter1 * baseK_), AscendC::Te::MakeShape(curM, curK0));
                AscendC::Te::Copy(copyL12L0, tensorAL0, tensorBlockAL1);

                // B L1->L0
                auto layoutBL0 = AscendC::Te::MakeZnLayout<TypeB>(curK0, curN);
                auto tensorBL0 =
                    AscendC::Te::MakeTensor(AscendC::Te::MakeL0BmemPtr<TypeB>(l0Offset * sizeof(TypeB)), layoutBL0);
                auto tensorBlockBL1 =
                    tensorBL1(AscendC::Te::MakeCoord(iter1 * baseK_, 0), AscendC::Te::MakeShape(curK0, curN));
                AscendC::Te::Copy(copyL12L0, tensorBL0, tensorBlockBL1);

                AscendC::SetFlag<AscendC::HardEvent::MTE1_M>(static_cast<uint16_t>(mte1Flag));
                AscendC::WaitFlag<AscendC::HardEvent::MTE1_M>(static_cast<uint16_t>(mte1Flag));

                // Original mmad parameters
                uint8_t unitFlag = 
                    enableL0cPingPong_ ?
                        0 :
                        ((iter0 + 1 == kL1Iter_ && iter1 + 1 == kL0Iter) ? FINAL_ACCUMULATION : NON_FINAL_ACCUMULATION);
                bool cmatrixInitVal = (iter0 == 0 && iter1 == 0);
                AscendC::Te::MmadParams mmadParams(curM, curN, curK0, unitFlag, cmatrixInitVal);
               
                // Pass custom Trait type
                AscendC::Te::Mad(
                    AscendC::Te::MmadAtom<AscendC::Te::MmadTraits<AscendC::Te::MmadOperation, MmadMmTraitConfig>>{},
                    tensorL0C, tensorAL0, tensorBL0, mmadParams);

                AscendC::SetFlag<AscendC::HardEvent::M_MTE1>(static_cast<uint16_t>(mte1Flag));
                l0PingPong_++;
            }
            AscendC::SetFlag<AscendC::HardEvent::MTE1_MTE2>(l1BufId);
            abL1LoopCnt_++;
        }
        if (enableL0cPingPong_) {
            AscendC::SetFlag<AscendC::HardEvent::M_FIX>(l0cPingPong_ & 0x1);
            AscendC::WaitFlag<AscendC::HardEvent::M_FIX>(l0cPingPong_ & 0x1);
        }

        // Move data to GM
        AscendC::Te::FixpipeParams fixpParams;
        fixpParams.unitFlag = enableL0cPingPong_ ? 0 : FINAL_ACCUMULATION;
        auto copyL0C2GM = AscendC::Te::MakeCopy(AscendC::Te::CopyL0C2GM{});
        AscendC::Te::Copy(copyL0C2GM, gmC, tensorL0C, fixpParams);

        if (enableL0cPingPong_) {
            AscendC::SetFlag<AscendC::HardEvent::FIX_M>(l0cPingPong_ & 0x1);
            l0cPingPong_++;
        }
    }

private:
    constexpr static uint16_t ZERO_FLAG = 0;
    constexpr static uint16_t FIRST_FLAG = 1;
    constexpr static uint16_t SIXTH_FLAG = 6;
    constexpr static uint16_t SEVENTH_FLAG = 7;
    uint64_t bL1Init_{0};
    uint64_t aL1OneBuffer_{1};
    uint64_t bL1OneBuffer_{1};
};
} // namespace Block

