/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file weight_quant_grouped_matmul_mxfp8fp4_block_scheduler_split_m.h
 * \brief N-resplit block scheduler for grouped matmul split-M execution.
 */
#pragma once

#include <cstdint>

namespace Block {

/*!
 * \brief Device-side tile enumerator for N-resplit + split-M execution.
 *
 * This scheduler consumes `Params` generated by host tiling and applies three
 * explicit scheduling principles:
 *
 * 1) Cross-group fair core rotation
 *    - `startBasicBlockId = (startBasicBlockId + prevTileNum) % coreNum`
 *      rotates the first basic block across groups.
 *    - The first tile for each core is aligned by `cubeBlockIdx` and
 *      `startBasicBlockId`, then advanced with `tileIdx += coreNum`.
 *    - Result: groups do not always start on the same cores.
 *
 * 2) M-direction core assignment by base block
 *    - For each group: `mBlkNum = ceil(mSize / baseM)`.
 *    - Then: `mStep = ceil(mSize / mBlkNum)`.
 *    - Total 2D tiles: `tileNum = mBlkNum * nBlockNum`.
 *    - Result: M workload is split into base-M-driven blocks and distributed by
 *      round-robin core stride.
 *
 * 3) N-direction policy coupled with host tiling strategy
 *    - Scheduler reconstructs three N segments from params:
 *      `nBlockNum = mainCount + firstTailCount + secondTailCount`,
 *      `seg1Base = mainCount * mainSize`,
 *      `seg2Base = seg1Base + firstTailCount * firstTailSize`.
 *    - Large-N (FullNumBlocks on host): tail block counts are organized to be
 *      core-count aligned (`coreNum` or `2 * coreNum` total tails), and two
 *      tail sizes are adjacent after C0 alignment, so tail workloads are close.
 *    - Small-N (NoFullNumBlocks on host): host may choose fewer N tasks than
 *      cores to keep each task's transfer/compute payload large enough.
 *
 * Runtime coordinate formulas:
 * - `mIdx = tileIdx / nBlockNum`, `nIdx = tileIdx % nBlockNum`
 * - `mOffset = mIdx * mStep`, `nOffset` from selected N segment
 * - `mL1Size = min(mStep, mSize - mOffset)`
 * - `nL1Size = min(segSize, nSize - nOffset)` (tail-safe clipping)
 *
 * Quick numeric example (using host-exported params):
 * - Assume:
 *   `coreNum=8`,
 *   `mainBlockCount=8`, `mainBlockSize=256`,
 *   `firstTailBlockCount=4`, `firstTailBlockSize=160`,
 *   `secondTailBlockCount=12`, `secondTailBlockSize=192`,
 *   `baseM=256`, `nSize=4992`, and one group has `mSize=1000`.
 * - Then:
 *   `nBlockNum=8+4+12=24`,
 *   `seg1Base=8*256=2048`,
 *   `seg2Base=2048+4*160=2688`,
 *   `mBlkNum=ceil(1000/256)=4`,
 *   `mStep=ceil(1000/4)=250`,
 *   `tileNum=4*24=96`.
 * - For a core with `tileIdx=13`:
 *   `mIdx=13/24=0`, `nIdx=13`,
 *   second-tail local index=`13-(8+4)=1`,
 *   `mOffset=0`, `nOffset=2688+1*192=2880`.
 * - Block shape:
 *   `mL1Size=min(250,1000-0)=250`,
 *   `nL1Size=min(192,4992-2880)=192`.
 */
template <typename ProblemShape_>
class GroupedMatmulSchedulerNResplit {
public:
    struct Params {
        uint64_t mainBlockCount;
        uint64_t mainBlockSize;
        uint64_t firstTailBlockCount;
        uint64_t firstTailBlockSize;
        uint64_t secondTailBlockCount;
        uint64_t secondTailBlockSize;
        uint64_t coreNum;
        uint64_t cubeNumBlocksN;
        int32_t baseM;
        uint64_t nSize;
    };

    using BlockShape = AscendC::Shape<int64_t, int64_t, int64_t, int64_t>;
    using BlockCoord = AscendC::Coord<int64_t, int64_t, int64_t, int64_t>;
    using ProblemShape = ProblemShape_;

    __aicore__ inline explicit GroupedMatmulSchedulerNResplit(const Params& params) : params_(params)
    {
        cubeBlockIdx_ = AscendC::GetBlockIdx();
        if ASCEND_IS_AIV {
            cubeBlockIdx_ = cubeBlockIdx_ >> 1;
        }

        nBlockNum_ = params_.mainBlockCount + params_.firstTailBlockCount + params_.secondTailBlockCount;
        seg01Count_ = params_.mainBlockCount + params_.firstTailBlockCount;
        seg1Base_ = params_.mainBlockCount * params_.mainBlockSize;
        seg2Base_ = seg1Base_ + params_.firstTailBlockCount * params_.firstTailBlockSize;
    }

    // Initialize per-group scheduling state before enumerating tiles for that group.
    __aicore__ inline void UpdateNextProblem(const ProblemShape& problemShape)
    {
        startBasicBlockId_ = (startBasicBlockId_ + prevTileNum_) % params_.coreNum;
        mSize_ = AscendC::Std::get<0>(problemShape);
        mBlkNum_ = CeilDiv(mSize_, static_cast<uint64_t>(params_.baseM));
        mStep_ = CeilDiv(mSize_, mBlkNum_);
        tileNum_ = mBlkNum_ * nBlockNum_;

        uint64_t first = cubeBlockIdx_ >= startBasicBlockId_ ? cubeBlockIdx_ : cubeBlockIdx_ + params_.coreNum;
        tileIdx_ = first - startBasicBlockId_;
        prevTileNum_ = tileNum_;
    }

    // Get the next tile coordinate assigned to the current core.
    __aicore__ inline bool GetTileIdx(BlockCoord& blockCoord)
    {
        if (tileIdx_ >= tileNum_) {
            return false;
        }

        uint64_t mIdx = tileIdx_ / nBlockNum_;
        uint64_t nIdx = tileIdx_ % nBlockNum_;
        uint64_t mOffset = mIdx * mStep_;
        uint64_t nOffset = 0;

        if (nIdx < params_.mainBlockCount) {
            nOffset = nIdx * params_.mainBlockSize;
        } else if (nIdx < seg01Count_) {
            uint64_t localIdx = nIdx - params_.mainBlockCount;
            nOffset = seg1Base_ + localIdx * params_.firstTailBlockSize;
        } else {
            uint64_t localIdx = nIdx - seg01Count_;
            nOffset = seg2Base_ + localIdx * params_.secondTailBlockSize;
        }

        AscendC::Std::get<0>(blockCoord) = static_cast<int64_t>(mOffset);
        AscendC::Std::get<1>(blockCoord) = static_cast<int64_t>(nOffset);

        tileIdx_ += params_.coreNum;
        return true;
    }

    // Compute tile shape from tile coordinate and segment-specific N split.
    __aicore__ inline BlockShape GetBlockShape(BlockCoord blockCoord)
    {
        uint64_t mOffset = static_cast<uint64_t>(AscendC::Std::get<0>(blockCoord));
        uint64_t nOffset = static_cast<uint64_t>(AscendC::Std::get<1>(blockCoord));

        uint64_t mL1Size = (mOffset + mStep_ > mSize_) ? (mSize_ - mOffset) : mStep_;

        uint64_t segSize = params_.secondTailBlockSize;
        if (nOffset < seg1Base_) {
            segSize = params_.mainBlockSize;
        } else if (nOffset < seg2Base_) {
            segSize = params_.firstTailBlockSize;
        }
        uint64_t nL1Size = (nOffset + segSize > params_.nSize) ? (params_.nSize - nOffset) : segSize;
        return {static_cast<int64_t>(mL1Size), static_cast<int64_t>(nL1Size), 0, 0};
    }

private:
    Params params_;

    uint64_t cubeBlockIdx_{0};

    // Derived segment constants.
    uint64_t seg01Count_{0};
    uint64_t seg1Base_{0};
    uint64_t seg2Base_{0};
    uint64_t nBlockNum_{0};

    // Per-group runtime state.
    uint64_t mSize_{0};
    uint64_t mBlkNum_{0};
    uint64_t mStep_{0};
    uint64_t tileNum_{0};
    uint64_t tileIdx_{0};

    // Cross-group rolling state.
    uint64_t startBasicBlockId_{0};
    uint64_t prevTileNum_{0};
};

} // namespace Block
