/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file weight_quant_grouped_matmul_mxfp8fp4_tiling_data.h
 * \brief Plain host tiling-data carrier for weight-quant grouped matmul.
 */
#pragma once

#include <cstdint>
#include <iostream>

/*!
 * \brief Host-to-device tiling contract for weight-quant grouped matmul.
 *
 * This struct is generated by host tiling
 * (`WeightQuantGroupedMatmulMxfp8fp4Tiling::GetTilingData`) and consumed by
 * `GroupedMatmulSchedulerNResplit::Params` on device.
 *
 * 1) Hardware-coupled inputs
 *    - `coreNum` is read from hardware AIC capability:
 *      `PlatformAscendCManager::GetInstance()->GetCoreNumAic()`.
 *    - `baseM` is fixed to 256 and used as the M-direction base split unit.
 *
 * 2) N-direction policy encoded into three segments
 *    - Segment model: `main + firstTail + secondTail`.
 *    - Branch conditions from `tiling.h`:
 *      a) `n % (coreNum * 256) == 0`:
 *         full main-block packing with `mainBlockSize = 256`.
 *      b) `n > coreNum * 128`:
 *         FullNumBlocks policy (prioritize core occupancy).
 *      c) otherwise:
 *         NoFullNumBlocks policy (prioritize task payload size for
 *         transfer/compute efficiency when N is small).
 *
 * 3) FullNumBlocks tail alignment property
 *    - Large-tail re-split:
 *      `firstTailBlockCount + secondTailBlockCount = 2 * coreNum`.
 *    - Normal tail split:
 *      `firstTailBlockCount + secondTailBlockCount = coreNum`.
 *    - Tail sizes are adjacent after C0 alignment (C0=32):
 *      `secondTailBlockSize = firstTailBlockSize + 32`.
 *      This keeps per-tail-block workload close.
 *
 * 4) Scheduler-facing semantics
 *    - `mainBlockCount` exported here is cross-core total main-block count
 *      (`SetBaseTiling`: `mainBlockCount = resplitMainCount * coreNum`).
 *    - `mainBlock*` / `firstTail*` / `secondTail*` plus `nSize` provide all
 *      constants required by scheduler to reconstruct N offsets and clip tails.
 *
 * Quick numeric example (FullNumBlocks):
 * - Given `coreNum=8`, `n=4992`.
 * - Since `4992 % (8*256) != 0` and `4992 > 8*128`, FullNumBlocks is selected.
 * - Host tiling derives:
 *   `mainBlockSize=256`, internal `mainBlockCount=1`,
 *   `firstTailBlockSize=160`, `firstTailBlockCount=4`,
 *   `secondTailBlockSize=192`, `secondTailBlockCount=12`.
 * - Exported `mainBlockCount` becomes `1 * coreNum = 8`.
 * - Coverage check:
 *   `8*256 + 4*160 + 12*192 = 4992`.
 */
struct WeightQuantGroupedMatmulTilingData {
    uint32_t groupNum = 0;             // Number of groups (experts).
    uint32_t coreNum = 0;              // Available AIC core count used by tiling.
    uint64_t kSize = 0;                // K dimension.
    uint64_t nSize = 0;                // Original N dimension.
    uint8_t cubeNumBlocksN = 0;        // Number of N-side block lanes mapped to cube blocks.
    uint32_t mainBlockSize = 0;        // Main N block size.
    uint64_t mainBlockCount = 0;       // Total number of main N blocks across cores.
    uint16_t firstTailBlockSize = 0;   // First tail segment N block size.
    uint16_t secondTailBlockSize = 0;  // Second tail segment N block size.
    uint16_t firstTailBlockCount = 0;  // Number of first tail blocks.
    uint16_t secondTailBlockCount = 0; // Number of second tail blocks.
    uint16_t baseM = 0;                // Base M tile size.

    void Print(std::ostream& os = std::cout, const char* prefix = "[WeightQuant GMM Tiling]") const
    {
        os << prefix << " groupNum=" << groupNum << ", coreNum=" << coreNum << ", kSize=" << kSize
           << ", nSize=" << nSize << std::endl;
        os << prefix << " cubeNumBlocksN=" << static_cast<uint32_t>(cubeNumBlocksN) << std::endl;
        os << prefix << " mainBlockSize=" << mainBlockSize << ", mainBlockCount=" << mainBlockCount
           << ", firstTailBlockSize=" << firstTailBlockSize << ", secondTailBlockSize=" << secondTailBlockSize
           << std::endl;
        os << prefix << " firstTailBlockCount=" << firstTailBlockCount
           << ", secondTailBlockCount=" << secondTailBlockCount << ", baseM=" << baseM << std::endl;
    }
};
